name: NicknameNight
main: com.xorinc.nick.NickNightPlugin
version: 0.0.2
author: drXor
website: http://github.com/drXor
description: >
    Bukkit plugin for wild nickname parties.
depend: [Essentials]
softdepend: []
commands: 
  nicknight:
    description: General plugin command
    permission: nicknight.use
    usage: /<command> [list]|stop|reload
permissions:
  nicknight.use:
      description: Allows use to /nicknight command
      default: op
  nicknight.reload:
      description: Reloads the config
      default: op